### ISSUE TITLE
SEDT error

### ISSUE THREAD

**Issue by chulmoon** [AppliedMathematicsANU/diamorse#7]
Hi, 

I am running SEDT on the .nc file of size about 800x500x800, but I get the message below. I checked that all the values of .nc files are either 0 or 1 (no negative values). When I run SEDT on a smaller sized (less than 800x500x800) .nc file, it worked fine. I wonder whether there is an upper limit for the image size to run SEDT. 

SEDT: ../lib/netcdf.hpp:708: int32_t anu_am::netcdf::BufferStream<Buffer>::readNonNegative() [with Buffer = anu_am::netcdf::FileBuffer; int32_t = int]: Assertion `val >= 0' failed.
Aborted (core dumped)

**Comment by odf** [comment]
Hi @chulmoon,

There is not really an upper limit for image size, as far as I am aware, other than that it fits into main memory and obviously that the compiler used has a 64-bit pointer type (which I assume is the case for all modern desktop/laptop systems).

There is however a limit on the size per individual file, as we are using the "classic" NetCDF 32-bit addressing mode, which effectively is reduced to 31-bits since address offsets are, according to the documentation, supposed to be signed integers. So that would limit the per-file size to approximately 2GB. To circumvent the problem, diamorse writes its output into multiple files of no more than 1GB each where necessary.

If you happened to use double precision floating point numbers in your input file, that would explain the problem. Any other data type should have worked with no issues, so in this case I'd need some more details about your system and maybe a full stack trace to say anything further.

The easiest solution in your case might be to switch to a different data type, as for example byte. Another is to split the file into smaller ones. That however requires adding some attributes to let diamorse know which part of the image is in which file. We have not documented this, but I am happy to write down what's required if necessary.

Obviously, if your file was created using one of the diamorse programs, you should not have this problem, either, so in that case please also let me know which program (with which inputs) was used.

**Comment by chulmoon** [comment]
Hi @odf, thanks for the reply. 
The original image file is .dat, so I did not use the diamorse programs. I converted them to .nc using Matlab. The size of the converted file (.nc) is 2.4GB, which is larger than 2GB. I tried again using the single precision numbers, but it did not work. 
In this case, do you recommend to convert the original .dat file into .pgm, run pgmtonc.C and run SEDT.C? You said the diamorse program will split the big-sized output files into the smaller ones.

**Comment by odf** [comment]
Going via `.pgm` is certainly worth a try. I don't think I've ever tried it for files this size, but if you run into problems, let me know and I'll do my best to fix them.

We could also try to whip up a quick diamorse converter for the `.dat` file if you know the format and it is simple enough (as the `.dat` extension would suggest). I've been thinking about adding support for "raw" data files, anyway, where the user would have to supply some basic information about the structure of the file (e.g. where does the data start, what are the dimensions, what is the data type, big or small endian, xyz or zyx order).

I'd also be interested in those `.nc` files Matlab produced. If you compress them, do they get small enough to email or share in some other way?

**Comment by chulmoon** [comment]
Hi @odf, 
I found a way to save .nc file as 'int8' using 'ncwrite' function in Matlab. The converted .nc file is now around 400MB, much less than before. I could run SEDT on the converted .nc files, split into two. 
By the way, if you provide a function to convert the "raw" data files to "nc" format, then it would be helpful for others.
I am facing a new problem in running the 'persistence.py'. Below is the error message that I got. Is it because of the insufficient RAM of the computer? How can I solve this issue?
Thank you very much.

starting with 3259453 critical cells

1401703 cancellations
  2147682 modifications
  456047 critical cells left
152168 cancellations
  590505 modifications
  151711 critical cells left
30213 cancellations
  196020 modifications
  91285 critical cells left
5124 cancellations
  51758 modifications
  81037 critical cells left
749 cancellations
  10780 modifications
  79539 critical cells left
86 cancellations
  1831 modifications
  79367 critical cells left
10 cancellations
  176 modifications
  79347 critical cells left
1 cancellations
  29 modifications
  79345 critical cells left
0 cancellations
Traceback (most recent call last):
  File "./python/persistence.py", line 174, in <module>
    pairs = fromVolumeFile(infile, options)
  File "./python/persistence.py", line 19, in fromVolumeFile
    weights = dict((tuple(v), x) for v, x in morse.weights())
  File "./python/persistence.py", line 19, in <genexpr>
    weights = dict((tuple(v), x) for v, x in morse.weights())
  File "MorseAnalysis.pyx", line 270, in weights (MorseAnalysis.cpp:5803)
MemoryError: std::bad_alloc

**Comment by odf** [comment]
Hi @chulmoon,

A problem with running `persistence.py` directly on a data file is that it keeps all the intermediate images in memory, which usually is not a good idea when the files get a bit larger. A better strategy is to run the individual C++ programs separately. The script https://github.com/AppliedMathematicsANU/diamorse/blob/master/scripts/compute-persistence does that for you. It will even include the SEDT step if the name of the original input file starts with `segmented_`. The end result is a text file (name starting with `persistence_`) containing the birth/death pairs for the simplified Morse complex. This can then be fed into `persistence.py` as usual to compute Betti numbers.

Obviously, even running things separately only gets you so far. There is unfortunately no way to process files in diamorse that are larger than the available memory.

**Comment by chulmoon** [comment]
Hi @odf 
Thank you very much for your help!
